  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - mc
      - tmux
      - lm-sensors
      - tlp
      - virtualbox
      - oneboard
      
   - name:run powertop
     tasks:
      - name:run powertop
        shell: powertop -n
        
    - name:run lm-sensors
     tasks:
      - name:run sensors-detect
        shell: sensors-detect -y
    
      
